
CREATE OR REPLACE TABLE AUDIT_LEDGER (
    DECISION_ID VARCHAR(64),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SHA256_STATE_HASH VARCHAR(64),
    FLEET_SIZE INT,
    COVERAGE_PCT DOUBLE,
    REASONING VARCHAR(500)
);
