
CREATE OR REPLACE TABLE PQ_AUDIT_LEDGER (
    DECISION_ID VARCHAR(64),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PQ_STATE_HASH VARCHAR(128),
    FLEET_SIZE INT,
    COVERAGE_PCT DOUBLE,
    REASONING VARCHAR(500)
);
